# Site settings

url: "https://www.yitaekhwang.com/"
#baseurl: "https://www.yitaekhwang.com/"
disqus-shortname: "yitaek"
lang: "en"
author: "Yitaek Hwang"
title: "In Search of Fatima"
description: "A fool's journey to nowhere. Yitaek' Hwang's personal blog for traveling, projects, and life blurbs"
keywords: "yitaek, hwang, traveling, tech, duke, vfa, leverege"
favicon: "/img/favicon.ico"


google-tracking-id: "UA-81478808-1"
force-https: True



################
# Header layout #
################

#black-favicon: "/img/favicon-world.ico"
background-img: "/img/space-small.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 1500
lines: # You can add HTML Tags in the Text
  - text: "In Search of Fatima"
  - text: "A fool's journey to nowhere"

me-img: "/img/paraglide.png" # Main image on the front page

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: True
pinterest-share: False
pocket-share: True
vkontakte-share: False


syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/leverege.png"
    date: "August 2016 - Present"
    description: "Started work as a Product Engineer at Leverege, an IoT company that develops software products that enable users to intelligently manage and visualize large sets of data."
  - image: "/img/timeline/vfalogo.jpg"
    date: "August 2016 - Present"
    description: "Started my two-year fellowship with Venture for America. VFA Fellows receive training and join a startup in an emerging US city to spark job growth and revitalization."
  - image: "/img/timeline/viflex.png"
    date: "August 2014 - May 2016"
    description: "Served as the CEO and Chief Engineer at ViFlex, LLC: a socially conscious venture that designs and manufactures low cost, self-adjustable eyeglasses for developing countries."
  - image: "/img/timeline/graduation.jpg"
    date: "August 2012 - May 2016"
    description: "Graduated magna cum laude with a dual degree in Electrical/Computer & Biomedical Engineering at Duke University"

# First image of the Timeline

timeline-img: "/img/timeline/masonlake.jpg"

###########
# Contact #
###########

email: "yitaek.hwang@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Yitaek is an aspiring machine learning engineer currently working at Leverege, LLC."
author_blurb_image: "/img/volcano.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/yitaek"
  - title: "instagram"
    url: "https://instagram.com/yitaek/"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/yitaekhwang"
  - title: "github"
    url: "https://github.com/yitaek"
  - title: "envelope"
    url: "mailto:yitaek.hwang@gmail.com"


############
# 404 page #
############

404-img: "/img/road.jpg"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Career: 'career'
  Travel: 'travel'
  Projects: 'projects'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
