
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://yitaek.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "https://yitaek.github.io"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Yitaek Hwang"
title: "In Searh of Fatima"
description: "A fool's journey to nowhere. Yitaek' Hwang's personal blog for traveling, projects, and life blurbs"
keywords: "yitaek, hwang, traveling, tech, duke, vfa, leverege"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon-world.ico"

background-img: "/img/space.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "In Search of Fatima"
  - text: "A fool's journey to nowhere"

me-img: "/img/paraglide.png" # Main image on the front page

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "yitaek"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/leverege.png"
    date: "August 2016 - Current"
    description: "Started Work as a Product Engineer at Leverege"
  - image: "/img/timeline/vfalogo.jpg"
    date: "August 2016 - Current"
    description: "Started my Two Year Fellowship with Venture for America"
  - image: "/img/timeline/graduation.jpg"
    date: "August 2012 - May 2016"
    description: "Studied Electrical/Computer & Biomedical Engineering at Duke University"

# First image of the Timeline

timeline-img: "/img/timeline/masonlake.jpg"

###########
# Contact #
###########

email: "yitaek.hwang@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Yitaek is an aspiring machine learning engineer currently working at Leverege, LLC."
author_blurb_image: "/img/volcano.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/yitaek"
  - title: "instagram"
    url: "https://instagram.com/yitaek/"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/yitaekhwang"
  - title: "github"
    url: "https://github.com/yitaek"


############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
